export const homeStr = {
    hello: 'Xin chào',
    overview: 'Tổng quan',
    report: 'Báo cáo',
    goal: 'Mục tiêu',
    loaded: 'Đã nạp',
    activity: 'Hoạt động',
    remainingCal: 'Lượng calo còn lại',
    trackDailyMenu: 'Theo dõi thực đơn hàng ngày',
    morning: 'Buổi sáng',
    afternoon: 'Buổi chiều',
    evening: 'Buổi tối',
    snack: 'Thức ăn nhanh',
    trackActivities: 'Theo dõi các hoạt động',
    footStep: 'Bước chân',
    exercise: 'Bài tập',
    drinkWater: 'Uống nước',
    trackWeight: 'Theo dõi cân nặng',
    recordWeight: 'Ghi lại cân nặng',
    highWeight: 'Cân nặng cao nhất',
    lowWeight: 'Cân nặng thấp nhất',
    averageWeight: 'Cân nặng trung bình',
    modeWeight: 'Cân nặng phổ biến',
    maintenanceWeight: 'Cân nặng duy trì',
    underWeight: 'Thiếu cân',
    healthyWeight: 'Khoẻ mạnh',
    overWeight: 'Thừa cân',
    obese: 'Béo phì cấp độ I',
    severelyObese: 'Béo phì cấp độ II',
    morbidlyObese: 'Béo phì cấp độ III',
    bmiInfo: 'Chỉ số khối cơ thể (BMI – Body Mass Index) là một thước đo dùng để đánh giá mức độ gầy hay béo của một người dựa trên cân nặng và chiều cao. Chỉ số này giúp ước lượng lượng mỡ trong cơ thể và được dùng để phân loại tình trạng cơ thể như thiếu cân, bình thường, thừa cân hay béo phì.',
    highestBmi: 'Chỉ số khối cơ thể cao nhất',
    lowestBmi: 'Chỉ số khối cơ thể thấp nhất',
    averageBmi: 'Chỉ số khối cơ thể trung bình',
    maintenanceBmi: 'Chỉ số khối cơ thể duy trì',
    bmi: 'Chỉ số khối cơ thể (BMI)',
    currentBmi: 'Chỉ số khối cơ thể hiện tại',
    dailyBmi: 'Chỉ số khối cơ thể hàng ngày',
};